version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./user_conf_new.d:/etc/nginx/conf.d
  #     - ./user_conf_new.d/certs:/etc/ssl
  #   depends_on:
  #     - myportfolio

volumes:
  mydatabase: